CREATE TABLE [dbo].[EXISTS_IN](
	[ITEMCODE] [int] NOT NULL,
	[STORECODE] [int] NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[AISLE_NO] [varchar](2) NOT NULL

	CONSTRAINT pk_EXISTS_IN PRIMARY KEY (ITEMCODE,STORECODE)
	CONSTRAINT fk_EXISTIN_ITEMCODE FOREIGN KEY (ITEMCODE)
		REFERENCES ITEM(ITEMCODE),
	CONSTRAINT fk_EXISTSIN_STORECODE FOREIGN KEY (STORECODE)
		REFERENCES STORE(STORECODE)

)