CREATE TABLE [dbo].[INCLUDES](
	[TRANSACTIONCODE] [int] NOT NULL,
	[ITEMCODE] [int] NOT NULL,
	[QUANTITY] [int] NOT NULL
	
	CONSTRAINT pk_INCLUDES PRIMARY KEY (TRANSACTIONCODE,ITEMCODE)
	CONSTRAINT fk_INCLUDES_TRANSACTIONCODE FOREIGN KEY (TRANSACTIONCODE)
		REFERENCES TRANSACTIONS(TRANSACTIONCODE),
	CONSTRAINT fk_INCLUDES_ITEMCODE FOREIGN KEY (ITEMCODE)
		REFERENCES ITEM(ITEMCODE)
)