CREATE TABLE [dbo].[PERSON](
	[PERSONCODE] [int] NOT NULL,
	[ADDRESSCODE] [int] NOT NULL,
	[FIRSTNAME] [VARCHAR](50) NOT NULL,
	[LASTNAME] [VARCHAR](50) NOT NULL,
	[EMAIL] [NVARCHAR](50) NOT NULL,
	[DOB] [DATE] NOT NULL
	
	CONSTRAINT pk_PERSON PRIMARY KEY (PERSONCODE)
	
	CONSTRAINT fk_PERSON_ADDRESSCODE FOREIGN KEY (ADDRESSCODE)
	REFERENCES ADDRESS(ADDRESSCODE)
)
