CREATE TABLE [dbo].[STORE](
	[STORECODE] [INT] NOT NULL,
	[ADDRESSCODE] [int] NOT NULL,
	[DEPARTMENTS] [VARCHAR](70) NOT NULL
	
	CONSTRAINT pk_STORE PRIMARY KEY (STORECODE)
	
	CONSTRAINT fk_STORE_ADDRESSCODE FOREIGN KEY (ADDRESSCODE)
	REFERENCES ADDRESS(ADDRESSCODE)

)