CREATE TABLE [dbo].[WORKS_IN](
	[PERSONCODE] [INT] NOT NULL,
	[STORECODE] [int] NOT NULL,
	[WEEKLY_HOURS]  [int] NOT NULL,
	[SINCE] [DATE] NOT NULL,
	[JOB] [VARCHAR](50) NOT NULL
	
	
	CONSTRAINT pk_WORKS_IN PRIMARY KEY (PERSONCODE)
	
	CONSTRAINT fk__WORKS_IN_PERSONCODE FOREIGN KEY (PERSONCODE)
		REFERENCES PERSON(PERSONCODE),
	CONSTRAINT fk__WORKS_IN_STORECODE FOREIGN KEY (STORECODE)
		REFERENCES STORE(STORECODE),
	CONSTRAINT fk__WORKS_IN_JOB FOREIGN KEY (JOB)
		REFERENCES POSITION(JOB)
	
)